### ISSUE TITLE
Error creating directory，but the upload file function can work normally

### ISSUE THREAD

**Issue by WeiJunFenYou** [EasyAbp/FileManagement#24]
[WRN] The type (Directory) of the file (a99dec3f-a51d-a1a7-2a47-39f6d0fbe5be) is unexpected, it should be RegularFile.
EasyAbp.FileManagement.Files.UnexpectedFileTypeException: The type (Directory) of the file (a99dec3f-a51d-a1a7-2a47-39f6d0fbe5be) is unexpected, it should be RegularFile.
   at EasyAbp.FileManagement.Files.FileManager.GetDownloadInfoAsync(File file)
   at EasyAbp.FileManagement.Files.FileAppService.CreateAsync(CreateFileInput input)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1.ProceedAsync()
   at Volo.Abp.Auditing.AuditingInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
   at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous[TResult](IInvocation invocation, IInvocationProceedInfo proceedInfo)

![KRZ84`K)WOMH8J3K9~AV0A6](https://user-images.githubusercontent.com/39354295/89419144-97660080-d763-11ea-9788-ef252a3368c0.png)

**Comment by gdlcf88** [comment]
How to reproduce it?

**Comment by gdlcf88** [comment]
This problem was fixed in https://github.com/EasyAbp/FileManagement/commit/374a854eb2708f8195c3b7e150a3e290b163b906, please upgrade the module to v0.4.1.
