### ISSUE TITLE
升级到1.6.0出错

### ISSUE THREAD

**Issue by liaozb** [EasyAbp/FileManagement#52]
Volo.Abp.AbpInitializationException: An error occurred during ConfigureServices phase of the module EasyAbp.FileManagement.EntityFrameworkCore.FileManagementEntityFrameworkCoreModule, EasyAbp.FileManagement.EntityFrameworkCore, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null. See the inner exception for details.
 ---> System.TypeLoadException: Method 'GetEnumerator' in type 'EasyAbp.FileManagement.Files.FileRepository' from assembly 'EasyAbp.FileManagement.EntityFrameworkCore, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at EasyAbp.FileManagement.EntityFrameworkCore.FileManagementEntityFrameworkCoreModule.<>c.<ConfigureServices>b__0_0(IAbpDbContextRegistrationOptionsBuilder options)
   at Microsoft.Extensions.DependencyInjection.AbpEfCoreServiceCollectionExtensions.AddAbpDbContext[TDbContext](IServiceCollection services, Action`1 optionsBuilder)
   at EasyAbp.FileManagement.EntityFrameworkCore.FileManagementEntityFrameworkCoreModule.ConfigureServices(ServiceConfigurationContext context)
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   --- End of inner exception stack trace ---
   at Volo.Abp.AbpApplicationBase.ConfigureServices()
   at Volo.Abp.AbpApplicationBase..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationWithExternalServiceProvider..ctor(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create(Type startupModuleType, IServiceCollection services, Action`1 optionsAction)
   at Volo.Abp.AbpApplicationFactory.Create[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionApplicationExtensions.AddApplication[TStartupModule](IServiceCollection services, Action`1 optionsAction)
   at Samruo.OA.Web.Startup.ConfigureServices(IServiceCollection services) in D:\projects\OA\src\Samruo.OA.Web\Startup.cs:line 10
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Samruo.OA.Web.Program.Main(String[] args) in D:\projects\OA\src\Samruo.OA.Web\Program.cs:line 31

**Comment by gdlcf88** [comment]
I have no idea what happened to your project, please provide a sample app to reproduce the problem.

By the way, ALWAYS make sure your app and its modules use the same version ABP framework.

**Comment by liaozb** [comment]
https://github.com/liaozb/BookStore  全新的项目也会出上面的错误

**Comment by liaozb** [comment]
我以为你把abp升级到5.0了。
